# Generated by Django 5.1.4 on 2024-12-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_student_is_staff_remove_teacher_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='newusers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newusers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newusers',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
