# Generated by Django 5.1.4 on 2024-12-17 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_student_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='myapp.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='myapp.class'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='myapp.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_periods', to='myapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.period'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='myapp.period'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='myapp.class')),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='myapp.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='sections',
            field=models.ManyToManyField(related_name='students', to='myapp.section'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='myapp.section'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects_teacher', to='myapp.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='myapp.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='myapp.subject'),
        ),
    ]
