# Generated by Django 5.1.4 on 2024-12-17 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_class_student_classes_teacher_classes_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='period',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
    ]
