# Generated by Django 5.1.4 on 2024-12-17 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_period_class_field_remove_period_teacher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='class_field',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='class_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='myapp.class'),
        ),
        migrations.AlterField(
            model_name='student',
            name='periods',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='myapp.period'),
        ),
        migrations.RemoveField(
            model_name='student',
            name='sections',
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='periods',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='myapp.period'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sections',
            field=models.ManyToManyField(blank=True, null=True, related_name='teachers', to='myapp.section'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_teachers', to='myapp.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.section'),
        ),
    ]
