# Generated by Django 5.1.4 on 2024-12-17 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_section_class_field_remove_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='myapp.class'),
        ),
    ]
