# Generated by Django 5.1.4 on 2024-12-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_period_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.period'),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='myapp.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_name',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='myapp.class'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='periods',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='myapp.period'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='myapp.section'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='myapp.subject'),
        ),
    ]
