# Generated by Django 5.1.4 on 2024-12-18 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_student_periods_alter_student_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user_type',
            field=models.CharField(default='Teacher', max_length=100),
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default='Principal', max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
