# Generated by Django 5.1.4 on 2024-12-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_teacher_user_type_principal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Class_name',
        ),
    ]
